name: CI clang format check

on:
  pull_request:
    types: [review_requested]

jobs:
  clang-format-check:

    runs-on: ubuntu-latest

    steps:
      - name: clang-format install
        run: apt install clang-format
      - name: clang-format
        run: clang-format -i -style=file '.*\.(cpp|h)$'
      - name: git diff
        run: git diff-index --quiet HEAD
